---
- name: Add a kernel parameter to GRUB_CMDLINE_LINUX
  ansible.builtin.replace:
      path: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX=".*)"'
      replace: '\1 acpi_enforce_resources=lax"'
  tags:
    - grub

- name: Add a kernel parameter to GRUB_CMDLINE_LINUX
  ansible.builtin.replace:
      path: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX=".*)"'
      replace: '\1 fbcon=font:TER16x32"'
  tags:
    - grub

- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  tags:
    - grub
