---
usb_sources:

  - name: mic
    description: "Samson Technologies Corp. GoMic compact condenser mic"
    subsystem: "sound"
    idVendor: "17a0"
    idProduct: "0305"
    devname: "snd/mic"

  - name: grabber
    description: "MACROSILICON WARRKY USB 3.0"
    subsystem: "video4linux"
    idVendor: "345f"
    idProduct: "2131"
    index: 0
    devname: "v4l/grabber"

  - name: wireless mic
    description: "SmartlinkTechnology 301a:1020"
    subsystem: "sound"
    idVendor: "301a"
    idProduct: "1020"
    index: 0
    devname: "snd/wireless"

