sd_port: 4033
room_name: gb

ExecStartPres:
  - "/usr/bin/gst-launch-1.0 videotestsrc num-buffers=3 ! ximagesink"

#  - "/usr/bin/gst-launch-1.0 alsasrc device=hw:W30 num-buffers=3 ! fakeaudiosink"

voctomix:
  version: main
  display_system: gl
  programoutput:
    videosink: autovideosink
    audiosink: fakeaudiosink
  previews: false
  mirrors: true
  framesize: [1280,720]
  framerate: 25
  audio_channels: 6
  auto_copy_recordings: false
  deburls: []

grub_settings:
  - [GRUB_CMDLINE_LINUX, "fbcon=font:TER16x32 console=tty0 console=ttyS0,115200n8"]
  - [GRUB_GFXPAYLOAD_LINUX, text]
  - [GRUB_GFXMODE, 640x480]
  - [GRUB_TERMINAL, serial]
  - [GRUB_SERIAL_COMMAND, "serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1"]
