sd_port: 4033
room_name: gb

ExecStartPres:
  - "/usr/bin/gst-launch-1.0 videotestsrc num-buffers=3 ! ximagesink"

;  - "/usr/bin/gst-launch-1.0 alsasrc device=hw:W30 num-buffers=3 ! fakeaudiosink"

voctomix:
  version: bugfix/falbacksrc
  display_system: gl
  programoutput:
    videosink: autovideosink
    # videosink: "videoconvert ! ximagesink"
    # audiosink: autoaudiosink
  previews: false
  mirrors: true
  framesize: [1280,720]
  framerate: 25
  auto_copy_recordings: false
  deburls: []


