---
voctomix:
  version: carlfk/gstsource
    # version: mv_sd_notify_ready
  display_system: gl
  programoutput:
    # videosink: autovideosink
    videosink: "videoconvert ! ximagesink"
    audiosink: autoaudiosink
  previews: false
  mirrors: true
  framesize: [1280,720]
  framerate: 25
  auto_copy_recordings: false
  deburls: []

stream_key: abc
