---

- name: Script to copy raw video files somewhere
  ansible.builtin.template:
    src: templates/systemd/videoteam-copy-recordings.j2
    dest: /usr/local/bin/videoteam-copy-recordings
    mode: "0755"

- name: Script to send commands to voctocore
  ansible.builtin.copy:
    src: files/systemd/videoteam-voctocore-cmds.py
    dest: /usr/local/bin/vidoeteam-voctocore-cmds.py
    mode: "0755"

- name: Install voctocore-cmds systemd units
  ansible.builtin.template:
    src: files/systemd/videoteam-voctocore-cmds.service
    dest: /etc/systemd/user/videoteam-voctocore-cmds.service
  notify: Systemd-reload

- name: Enable voctocore-cmds systemd unit
  ansible.builtin.systemd_service:
    name: "videoteam-voctocore-cmds"
    scope: global
    enabled: true

- name: Start voctocore-cmds systemd units
  ansible.builtin.systemd_service:
    name: "videoteam-voctocore-cmds"
    scope: global
    daemon_reload: true
    daemon_reexec: true
