---
  # directories & code
  - name: create voctomix directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/voctomix2/scripts/
      - /opt/voctomix2/release/

  - name: checkout voctomix release
  # git: repo=https://c3voc.de/git/voctomix
  # git: repo=https://github.com/voc/voctomix/
    git: repo=https://github.com/CarlFK/voctomix
         dest=/opt/voctomix2/release/
         force=yes
         version={{ voctomix.version }}
         accept_hostkey=yes

  - name: merge my 2 PRs
    ansible.builtin.script:
      chdir: /opt/voctomix2/release
      cmd: files/scripts/git_merge.sh carlfk/gstsource origin/mv_sd_notify_ready
    tags:
      - vocto
    when: false

  - name: Create a symbolic link to core
    ansible.builtin.file:
      src: /opt/voctomix2/release/voctocore/voctocore.py
      dest: /usr/bin/voctocore
      state: link
    when: false

  - name: Create a symbolic link to gui
    ansible.builtin.file:
      src: /opt/voctomix2/release/voctogui/voctogui.py
      dest: /usr/bin/voctogui
      state: link
    when: false

  - name: remove voctomix2 default config
    ansible.builtin.file:
      path: /opt/voctomix2/release/voctocore/default-config.ini
      state: absent
