---
- name: Install voctomix & related packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - voctomix
      - voctomix-outcasts
      - gstreamer1.0-libcamera
      - gstreamer1.0-libav
      # - gstreamer1.0-pulseaudio
      # - gstreamer1.0-pipewire
      # - gstreamer1.0-gl
      - systemd
      - vim

- name: Create voctomix config dir
  ansible.builtin.file:
    path: /etc/voctomix
    state: directory

- name: Configure voctomix
  ansible.builtin.template:
    src: templates/etc/{{ item }}.j2
    dest: /etc/voctomix/{{ item }}
  with_items:
    - voctocore.ini

- name: Create recording directory
  ansible.builtin.file:
    state: directory
    dest: /srv/video/{{ org }}/{{ show }}/dv/{{ room_name }}
    recurse: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Push the static scripts
  ansible.builtin.copy:
    src: files/systemd/videoteam-{{ item }}
    dest: /usr/local/bin/videoteam-{{ item }}
    mode: "0755"
  with_items:
    - record-timestamp-ts
    - record-timestamp-mp4
    - local-monitor-video.sh
    - local-monitor-audio.sh
    - voctocore-cmds.py

- name: Script to copy raw video files somewhere
  ansible.builtin.template:
    src: templates/systemd/videoteam-copy-recordings.j2
    dest: /usr/local/bin/videoteam-copy-recordings
    mode: "0755"

- name: Install voctomix recording systemd units
  ansible.builtin.template:
    src: templates/systemd/videoteam-{{ item }}.j2
    dest: /etc/systemd/system/videoteam-{{ item }}
  with_items:
    - voctocore.service
    - voctocore-cmds.service
    - record.service
    - cutlist.service
    - local-monitor-audio.service
      # - local-monitor-video.service
  notify: Systemd-reload

- name: Enable voctomix systemd units
  ansible.builtin.systemd_service:
    name: videoteam-{{ item }}
    enabled: true
  with_items:
    - voctocore.service
    - voctocore-cmds.service
    - record.service
    - cutlist.service
    - local-monitor-audio.service
      # - local-monitor-video.service
  tags:
    - test_voc

- name: Start voctomix systemd units
  ansible.builtin.systemd_service:
    name: videoteam-{{ item }}
    state: started
    daemon_reload: true
  with_items:
    - voctocore.service
    - voctocore-cmds.service
    - record.service
    - cutlist.service
    - local-monitor-audio.service
      # - local-monitor-video.service

- name: Install voctomix video monitor script
  ansible.builtin.template:
    src: templates/systemd/videoteam-{{ item }}.j2
    dest: /etc/systemd/user/videoteam-{{ item }}
  with_items:
    - local-monitor-video.service
  notify: Systemd-reload

- name: Enable voctomix video systemd units
  ansible.builtin.systemd_service:
    name: videoteam-{{ item }}
    scope: user
    enabled: true
  with_items:
    - local-monitor-video.service
  tags:
    - test_one_voc

- name: Start voctomix video systemd units
  ansible.builtin.systemd_service:
    name: videoteam-{{ item }}
    scope: user
    state: started
    daemon_reload: true
  with_items:
    - local-monitor-video.service
  when: false

