---
- name: Install libcamera and stuff
  ansible.builtin.apt:
    update_cache: yes
    name:
      - libcamera-tools
        # - linux-firmware # ubuntu package name
      - firmware-intel-graphics # Binary firmware for Intel iGPUs and IPUs
      - firmware-intel-misc # Binary firmware for miscellaneous Intel devices and chips
      - firmware-nonfree

  tags:
    - cam

        # [    4.392510] ipu3_imgu: module is from the staging directory, the quality is unknown, you have been warned.

