---
- name: Install fonts
  ansible.builtin.apt:
    name:
      - console-data
      - consolefonts-bedstead
      - fonts-ubuntu-console
      - fonty-rg
      - psf-unifont

  tags:
    - console

- name: console big font
  ansible.builtin.copy:
    src: files/etc/default/console-setup
    dest: /etc/default/console-setup
  tags:
    - console
