---
- {ansible.builtin.include_tasks: sugar.yml }
- {ansible.builtin.include_tasks: sudoers.yml, when: true }
- {ansible.builtin.include_tasks: hostname.yml, tags: [hostname] }
- {ansible.builtin.include_tasks: overlayroot.yml, when: false }
- {ansible.builtin.include_tasks: aptproxy.yml, when: true }
- {ansible.builtin.include_tasks: bashrc.yml, tags: [bashrc] }
