---

- name: Install handy packages
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
    allow_unauthenticated: false
    name:
      - ack
      - dcfldd
      - git
      - nmap
      - p7zip-full
      - pmount
      - python3-lxml
      - telnet
      - tmux
      - vim
