---

- name: Install handy packages
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
    allow_unauthenticated: false
    name:
      - vim
      - ack
      - git
      - tmux
      - pmount
      - dcfldd
      - p7zip-full
      - python3-lxml
