---
- hosts: gb
  roles:
  - apt
  - helpers
  - xfce-desktop
  - voctomix
  - sidedoor

- hosts: opi
  roles:
  - fixopi

- hosts: d7212
  roles:
  - devices
  - fix7212

- hosts: test
  roles:
  - apt
